In [7]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

## Tratamento

In [8]:
csv = pd.read_csv('dados/precos-gasolina-etanol-07.csv', delimiter=';')
comb_jul = pd.DataFrame(csv)
comb_jul.head(1)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,ES,COLATINA,SAO FRANCISCO DE ASSIS COMERCIO DE COMBUSTIVEI...,08.519.545/0001-10,PRACA FIDELIS FERRARI,35,NaN,LACE,29703-030,GASOLINA ADITIVADA,01/07/2022,"7,48",NaN,R$ / litro,VIBRA ENERGIA

In [9]:
csv = pd.read_csv('dados/precos-gasolina-etanol-08.csv', delimiter=';')
comb_ago = pd.DataFrame(csv)
comb_ago.head(1)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,AUTO POSTO M M GARROTE LTDA,08.738.994/0001-50,RODOVIA AL-220,5848,KM 96,BOM SUCESSO,57309-035,ETANOL,01/08/2022,"4,79",NaN,R$ / litro,VIBRA ENERGIA

In [10]:
conjunto_dados = pd.concat([comb_jul, comb_ago])
conjunto_dados.head(1)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,ES,COLATINA,SAO FRANCISCO DE ASSIS COMERCIO DE COMBUSTIVEI...,08.519.545/0001-10,PRACA FIDELIS FERRARI,35,NaN,LACE,29703-030,GASOLINA ADITIVADA,01/07/2022,"7,48",NaN,R$ / litro,VIBRA ENERGIA

In [11]:
conjunto_dados.reset_index(0,drop=True,inplace=True)

In [12]:
((conjunto_dados.isnull().sum() / conjunto_dados.shape[0]) * 100).sort_values(ascending=False)

Valor de Compra      100.000000
Complemento           78.707461
Bairro                 0.323960
Numero Rua             0.055828
Regiao - Sigla         0.000000
Estado - Sigla         0.000000
Municipio              0.000000
Revenda                0.000000
CNPJ da Revenda        0.000000
Nome da Rua            0.000000
Cep                    0.000000
Produto                0.000000
Data da Coleta         0.000000
Valor de Venda         0.000000
Unidade de Medida      0.000000
Bandeira               0.000000
dtype: float64

In [13]:
conjunto_dados.drop('Valor de Compra', axis=1, inplace=True)

In [14]:
conjunto_dados['Valor de Venda'] = conjunto_dados['Valor de Venda'].apply(lambda y: float(str(y.replace(',','.'))))

In [15]:
conjunto_dados.Complemento.fillna('0', inplace=True)

In [16]:
conjunto_dados.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,SE,ES,COLATINA,SAO FRANCISCO DE ASSIS COMERCIO DE COMBUSTIVEI...,08.519.545/0001-10,PRACA FIDELIS FERRARI,35,0,LACE,29703-030,GASOLINA ADITIVADA,01/07/2022,7.48,R$ / litro,VIBRA ENERGIA
1,SE,ES,COLATINA,SAO FRANCISCO DE ASSIS COMERCIO DE COMBUSTIVEI...,08.519.545/0001-10,PRACA FIDELIS FERRARI,35,0,LACE,29703-030,GASOLINA,01/07/2022,7.38,R$ / litro,VIBRA ENERGIA
2,SE,ES,COLATINA,POSTO MOTOCAP LTDA,04.814.652/0001-10,PRACA ALMIRANTE BARROSO,52,LETRA A,LACE,29703-055,ETANOL,01/07/2022,5.99,R$ / litro,VIBRA ENERGIA
3,SE,ES,COLATINA,POSTO MOTOCAP LTDA,04.814.652/0001-10,PRACA ALMIRANTE BARROSO,52,LETRA A,LACE,29703-055,GASOLINA,01/07/2022,7.39,R$ / litro,VIBRA ENERGIA
4,CO,GO,GOIANIA,JUSTINIANO & JUSTINIANO LTDA,04.489.287/0001-16,AVENIDA JOSE LEANDRO DA CRUZ,"2,36","QUADRA 18, LOTE 01",PARQUE AMAZONIA,74840-390,GASOLINA ADITIVADA,01/07/2022,6.49,R$ / litro,IPIRANGA

In [17]:
conjunto_dados['Data da Coleta'] = pd.to_datetime(conjunto_dados['Data da Coleta'],format='%d/%m/%Y')
conjunto_dados.head(1)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,SE,ES,COLATINA,SAO FRANCISCO DE ASSIS COMERCIO DE COMBUSTIVEI...,08.519.545/0001-10,PRACA FIDELIS FERRARI,35,0,LACE,29703-030,GASOLINA ADITIVADA,2022-07-01,7.48,R$ / litro,VIBRA ENERGIA

In [18]:
conjunto_dados.loc[(conjunto_dados['Data da Coleta'] > '2022-07-11') & (conjunto_dados['Data da Coleta'] < '2022-07-15')]

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
18585,S,RS,PORTO ALEGRE,COMERCIAL DE COMBUSTIVEIS TK LTDA,91.438.796/0001-14,RUA EDUARDO PRADO,415,CAVALHADA,CAVALHADA,91751-000,GASOLINA ADITIVADA,2022-07-12,6.09,R$ / litro,RAIZEN
18586,S,RS,PORTO ALEGRE,COMERCIAL DE COMBUSTIVEIS TK LTDA,91.438.796/0001-14,RUA EDUARDO PRADO,415,CAVALHADA,CAVALHADA,91751-000,GASOLINA,2022-07-12,5.89,R$ / litro,RAIZEN
18587,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,LOTEAMENTO PORTAL DA AMAZONIA,S/N,"QUADRA 101 LTS 01,02,03,04, 05 E 33",CALAFATE,69905-801,GASOLINA ADITIVADA,2022-07-12,6.39,R$ / litro,VIBRA ENERGIA
18588,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,LOTEAMENTO PORTAL DA AMAZONIA,S/N,"QUADRA 101 LTS 01,02,03,04, 05 E 33",CALAFATE,69905-801,ETANOL,2022-07-12,5.59,R$ / litro,VIBRA ENERGIA
18589,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,LOTEAMENTO PORTAL DA AMAZONIA,S/N,"QUADRA 101 LTS 01,02,03,04, 05 E 33",CALAFATE,69905-801,GASOLINA,2022-07-12,6.39,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28444,NE,BA,IRECE,AUTO POSTO NORDESTE LTDA,35.621.319/0001-19,RUA BELEM,S/N,TERREO,BAIXAO DE SINEZIA,44900-000,GASOLINA ADITIVADA,2022-07-14,6.19,R$ / litro,BRANCA
28445,NE,PE,RECIFE,HCW COMERCIO DE COMBUSTIVEIS E LUBRIFICANTES LTDA,33.172.272/0003-90,RUA GENERAL JOAQUIM INACIO,425,0,PAISSANDU,50070-495,GASOLINA,2022-07-14,6.35,R$ / litro,IPIRANGA
28446,NE,PE,RECIFE,HCW COMERCIO DE COMBUSTIVEIS E LUBRIFICANTES LTDA,33.172.272/0003-90,RUA GENERAL JOAQUIM INACIO,425,0,PAISSANDU,50070-495,ETANOL,2022-07-14,5.79,R$ / litro,IPIRANGA
28447,S,SC,FLORIANOPOLIS,VIP COMBUSTIVEIS LTDA,35.793.154/0001-62,RUA WALDEMAR OURIQUES,739,0,CAPOEIRAS,88090-050,GASOLINA,2022-07-14,5.96,R$ / litro,BRANCA
28448,S,SC,FLORIANOPOLIS,VIP COMBUSTIVEIS LTDA,35.793.154/0001-62,RUA WALDEMAR OURIQUES,739,0,CAPOEIRAS,88090-050,GASOLINA ADITIVADA,2022-07-14,5.96,R$ / litro,BRANCA

In [19]:
conjunto_dados.dtypes

Regiao - Sigla               object
Estado - Sigla               object
Municipio                    object
Revenda                      object
CNPJ da Revenda              object
Nome da Rua                  object
Numero Rua                   object
Complemento                  object
Bairro                       object
Cep                          object
Produto                      object
Data da Coleta       datetime64[ns]
Valor de Venda              float64
Unidade de Medida            object
Bandeira                     object
dtype: object

In [20]:
#conjunto_dados['Data da Coleta'] = conjunto_dados['Data da Coleta'].dt.strftime('%d-%m-%Y')
#conjunto_dados.head(1)

In [21]:
conjunto_dados['Data da Coleta'][0]

Timestamp('2022-07-01 00:00:00')

## Trabalhando nos dados

In [87]:
# 7. Qual a região que possui o maior valor médio da gasolina?

# Criando um recorte do DF original onde temos apenas os registros da Gasolina
df_gas = conjunto_dados.loc[(conjunto_dados['Produto'] == 'gasolina'.upper()), :]

In [88]:
df_gas.groupby(['Regiao - Sigla', 'Produto'])[['Valor de Venda']].mean().sort_values(by='Valor de Venda', ascending=False)

                         Valor de Venda
Regiao - Sigla Produto
N              GASOLINA        5.972082
NE             GASOLINA        5.955809
S              GASOLINA        5.641161
SE             GASOLINA        5.615655
CO             GASOLINA        5.581603

In [89]:
# 8. Qual a região que possui o menor valor médio do etanol?

# Criando um recorte do DF original onde temos apenas os registros do Etanol
df_et = conjunto_dados.loc[(conjunto_dados['Produto'] == 'etanol'.upper()), :]

In [93]:
df_et.groupby(['Regiao - Sigla', 'Produto'])[['Valor de Venda']].mean().sort_values(by='Valor de Venda', ascending=True)

                        Valor de Venda
Regiao - Sigla Produto
CO             ETANOL         4.107305
SE             ETANOL         4.149964
S              ETANOL         4.842372
NE             ETANOL         5.246069
N              ETANOL         5.340633